import { Leaf, Recycle, Fuel as Co2, Trees, Factory, ArrowUpRight, BarChart2, Download } from "lucide-react";
import TopBar from "../../navbar/topbar";
// import TopBar from "../../../../public/icon";
import Footer from "../../navbar/footer";
import { useState } from 'react';
import { jsPDF } from 'jspdf';


const Sostenibilita = () => {

    const [isDownloading, setIsDownloading] = useState(false);
    const generatePDF = () => {
        const doc = new jsPDF();
        doc.setFont('helvetica');
        doc.setFontSize(20);
        doc.setTextColor(40, 53, 147);

        const img = new Image();
        // img.src = '../../../../public/icon.png'; 
        // doc.addImage(img, 'PNG', 15, 15, 30, 30);

        doc.setFontSize(22);
        doc.text('Report di Sostenibilità 2023', 50, 30);

        let yPosition = 50;

        doc.setFontSize(16);
        doc.setTextColor(40, 53, 147);
        doc.text('Dati Annuali:', 15, yPosition);

        annualData.forEach((data, index) => {
            yPosition += 10;
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(
                `${data.year}: CO₂ ${data.co2} ton | Acqua ${data.water}m³ | Rifiuti ${data.waste}kg`,
                20,
                yPosition
            );
        });

        yPosition += 20;
        doc.setFontSize(16);
        doc.setTextColor(40, 53, 147);
        doc.text('Obiettivi:', 15, yPosition);

        targets.forEach((target, index) => {
            yPosition += 10;
            doc.setFontSize(12);
            doc.setTextColor(0, 0, 0);
            doc.text(
                `${target.title} (${target.targetYear}): ${target.progress}% completato`,
                20,
                yPosition
            );
            yPosition += 6;
            doc.text(target.description, 25, yPosition);
        });
        const footerY = doc.internal.pageSize.height - 20;
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text('Generated by JustWeed - ' + new Date().toLocaleDateString(), 15, footerY);

        return doc;
    };

    const handleDownload = async () => {
        try {
            setIsDownloading(true);
            const pdf = generatePDF();
            await new Promise(resolve => setTimeout(resolve, 1500));
            pdf.save(`JustWeed_Report_${new Date().getFullYear()}.pdf`);
            console.log('Download completato:', new Date().toISOString());
            // window.analytics.track('ReportDownloaded', { version: '2023' });

        } catch (error) {
            console.error('Errore nel download:', error);
            alert('Si è verificato un errore durante il download');
        } finally {
            setIsDownloading(false);
        }
    };

    const annualData = [
        { year: 2023, co2: 125, water: 85, waste: 90 },
        { year: 2022, co2: 150, water: 120, waste: 110 },
        { year: 2021, co2: 180, water: 150, waste: 130 }
    ];

    const targets = [
        {
            title: "Carbon Neutral",
            description: "Raggiungere zero emissioni nette",
            progress: 65,
            targetYear: 2025,
            color: "bg-gradient-to-r from-green-500 to-teal-500"
        },
        {
            title: "Zero Waste",
            description: "Divertire il 100% dei rifiuti dalle discariche",
            progress: 78,
            targetYear: 2024,
            color: "bg-gradient-to-r from-blue-500 to-purple-500"
        },
        {
            title: "Water Positive",
            description: "Restituire più acqua di quella consumata",
            progress: 42,
            targetYear: 2026,
            color: "bg-gradient-to-r from-cyan-500 to-sky-500"
        }
    ];

    return (
        <div className="min-h-screen bg-gradient-to-br from-base-100 to-base-200 text-white">
            <TopBar />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
                <div className="text-center mb-12">
                    <div className="lg:mr-10 inline-flex items-center gap-2 bg-blue-900/20 px-4 py-2 rounded-full mb-4 border border-blue-900/30">
                        <Leaf size={18} className="text-green-400" />
                        <span className="text-green-400">Report 2023</span>
                    </div>
                    <div className="flex justify-center">
                        <h1 className="text-5xl font-bold text-center text-transparent bg-clip-text bg-clip-text bg-gradient-to-r from-green-400 to-cyan-500 animate-gradient leading-normal">
                            Report di Sostenibilità
                        </h1>
                    </div>

                    <p className="text-gray-300 max-w-3xl mx-auto text-lg">
                        Il nostro impegno concreto per un futuro rigenerativo. Scopri i traguardi raggiunti e gli obiettivi per i prossimi anni.
                    </p>
                </div>

                <div className="bg-base-200 rounded-xl p-6 border border-blue-900/30 shadow-lg mb-12 flex flex-col md:flex-row justify-between items-center gap-6">
                    <div className="flex items-center gap-4">
                        <div className="bg-gradient-to-r from-green-500/20 to-cyan-500/20 p-3 rounded-xl">
                            <Download className="text-cyan-400" size={28} />
                        </div>
                        <div>
                            <h3 className="font-bold text-lg">Scarica il report completo</h3>
                            <p className="text-sm text-gray-300">PDF 2023 | Ultimo aggiornamento: Maggio 2024</p>
                        </div>
                    </div>
                    <button
                        className={`btn bg-gradient-to-r from-green-500 to-cyan-600 hover:from-green-600 hover:to-cyan-700 border-none text-white gap-2 ${isDownloading ? 'loading' : ''
                            }`}
                        onClick={handleDownload}
                        disabled={isDownloading}
                    >
                        {!isDownloading && <Download size={18} />}
                        {isDownloading ? 'Generando...' : 'Download Report'}
                    </button>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
                    {[
                        {
                            icon: <Co2 size={24} className="text-green-400" />,
                            title: "Emissioni CO₂",
                            value: "-32%",
                            description: "riduzione dal 2021",
                            chart: <BarChart2 className="text-cyan-400" size={36} />
                        },
                        {
                            icon: <Recycle size={24} className="text-green-400" />,
                            title: "Rifiuti Riciclati",
                            value: "94%",
                            description: "dei nostri scarti",
                            chart: <Recycle className="text-cyan-400" size={36} />
                        },
                        {
                            icon: <Trees size={24} className="text-green-400" />,
                            title: "Energia Verde",
                            value: "100%",
                            description: "rinnovabile",
                            chart: <Leaf className="text-cyan-400" size={36} />
                        }
                    ].map((metric, i) => (
                        <div key={i} className="bg-card-base-100 p-6 rounded-xl border border-blue-900/30 hover:border-cyan-500/50 transition-all hover:-translate-y-1 shadow-md">
                            <div className="flex items-center gap-3 mb-4">
                                {metric.icon}
                                <h3 className="font-bold text-lg">{metric.title}</h3>
                            </div>
                            <div className="flex justify-between items-end">
                                <div>
                                    <p className="text-3xl font-bold bg-gradient-to-r from-green-400 to-cyan-500 bg-clip-text text-transparent">
                                        {metric.value}
                                    </p>
                                    <p className="text-gray-300 text-sm">{metric.description}</p>
                                </div>
                                {metric.chart}
                            </div>
                        </div>
                    ))}
                </div>
                <div className="bg-card-base-100 rounded-xl border border-blue-900/30 p-8 mb-12 shadow-lg">
                    <h2 className="text-2xl font-bold mb-8 flex items-center gap-3">
                        <Factory className="text-cyan-400" size={28} />
                        <span className="bg-gradient-to-r from-green-400 to-cyan-500 bg-clip-text text-transparent">
                            Obiettivi Strategici
                        </span>
                    </h2>

                    <div className="space-y-8">
                        {targets.map((target, index) => (
                            <div key={index} className="group">
                                <div className="flex justify-between items-start mb-4">
                                    <div>
                                        <h3 className="font-bold text-lg mb-1">{target.title}</h3>
                                        <p className="text-gray-300">{target.description}</p>
                                    </div>
                                    <span className={`badge ${target.color} text-white border-none`}>
                                        Target {target.targetYear}
                                    </span>
                                </div>
                                <div className="flex items-center gap-4">
                                    <div className="flex-1">
                                        <progress
                                            className={`progress ${target.color.replace('bg-gradient-to-r', 'progress')} h-3`}
                                            value={target.progress}
                                            max="100"
                                        />
                                    </div>
                                    <span className="text-sm bg-gradient-to-r from-green-400 to-cyan-500 bg-clip-text text-transparent font-bold">
                                        {target.progress}%
                                    </span>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="bg-card-base-100 rounded-xl border border-blue-900/30 p-8 mb-12 shadow-lg">
                    <h2 className="text-2xl font-bold mb-8 bg-gradient-to-r from-green-400 to-cyan-500 bg-clip-text text-transparent">
                        Progresso Annuale
                    </h2>

                    <div className="overflow-x-auto">
                        <table className="table w-full">
                            <thead>
                                <tr className="border-b border-blue-900/30">
                                    <th className="bg-card-base-100 text-gray-300 font-semibold">Anno</th>
                                    <th className="bg-card-base-100 text-gray-300 font-semibold">CO₂ (ton)</th>
                                    <th className="bg-card-base-100 text-gray-300 font-semibold">Acqua (m³)</th>
                                    <th className="bg-card-base-100 text-gray-300 font-semibold">Rifiuti (kg)</th>
                                </tr>
                            </thead>
                            <tbody>
                                {annualData.map((data, index) => (
                                    <tr key={index} className="hover:bg-blue-900/10 border-b border-blue-900/30">
                                        <td className="font-medium">{data.year}</td>
                                        {['co2', 'water', 'waste'].map((metric, i) => (
                                            <td key={i}>
                                                <div className="flex items-center gap-2">
                                                    <span>{data[metric]}</span>
                                                    {index > 0 && (
                                                        <span className={`text-xs ${data[metric] < annualData[index - 1][metric] ?
                                                                'text-green-400' : 'text-red-400'
                                                            }`}>
                                                            ({((data[metric] - annualData[index - 1][metric]) / annualData[index - 1][metric] * 100).toFixed(0)}%)
                                                        </span>
                                                    )}
                                                </div>
                                            </td>
                                        ))}
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>

                <div className="mb-12">
                    <h2 className="text-2xl font-bold mb-8 bg-gradient-to-r from-green-400 to-cyan-500 bg-clip-text text-transparent">
                        Nostre Iniziative
                    </h2>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        {[
                            {
                                icon: <Trees className="text-green-400" size={24} />,
                                title: "Riforestazione",
                                content: "Abbiamo piantato 5.000 alberi nel 2023 per compensare le emissioni residue e supportare la biodiversità locale.",
                                color: "from-green-500/20 to-teal-500/20"
                            },
                            {
                                icon: <Recycle className="text-green-400" size={24} />,
                                title: "Economia Circolare",
                                content: "Programma di recupero dei materiali che ha ridotto del 40% i nuovi acquisti di materie prime vergini.",
                                color: "from-blue-500/20 to-purple-500/20"
                            }
                        ].map((initiative, i) => (
                            <div key={i} className="bg-card-base-100 rounded-xl border border-blue-900/30 p-6 hover:border-cyan-500/50 transition-all hover:-translate-y-1 shadow-md group">
                                <div className="flex items-start gap-4 mb-4">
                                    <div className={`bg-gradient-to-r ${initiative.color} p-3 rounded-xl`}>
                                        {initiative.icon}
                                    </div>
                                    <div>
                                        <h3 className="font-bold text-lg mb-2">{initiative.title}</h3>
                                        <p className="text-gray-300">{initiative.content}</p>
                                    </div>
                                </div>
                                <a href="#" className="text-cyan-400 text-sm flex items-center gap-1 hover:text-green-400 transition-colors">
                                    Scopri di più <ArrowUpRight size={16} className="group-hover:translate-x-1 transition-transform" />
                                </a>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="bg-card-base-100 rounded-xl p-8 border border-blue-900/30 shadow-lg">
                    <h2 className="text-2xl font-bold mb-6 text-center bg-gradient-to-r from-green-400 to-cyan-500 bg-clip-text text-transparent">
                        Certificazioni
                    </h2>
                    <p className="text-gray-300 max-w-2xl mx-auto text-center mb-8">
                        Il nostro impegno è riconosciuto dai principali standard internazionali di sostenibilità
                    </p>
                    <div className="flex flex-wrap justify-center gap-4">
                        {['B Corp', 'Carbon Neutral', 'ISO 14001', 'LEED Gold'].map((cert, index) => (
                            <div key={index} className="badge badge-lg bg-gradient-to-r from-green-500/20 to-cyan-500/20 text-cyan-400 border-cyan-500/30 gap-2 px-4 py-3">
                                {cert}
                            </div>
                        ))}
                    </div>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default Sostenibilita;